services:
        #nginx:
        #image: nginx:latest
        #ports:
        #- "80:80"
        #- "443:443"
        #volumes:
        #- ./nginx.conf:/etc/nginx/nginx.conf
        #- ./deploy-test.conf:/etc/nginx/conf.d/deploy-test.conf
        #networks:
        #- shared_network

  frontend:
    image: seminss/gongtong_frontend:latest
    container_name: gongtong_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - shared_network
  
  tastyties:
    image: seminss/tastyties:latest
    container_name: tastyties
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      SERVER_PORT: 8080
      OPENVIDU_URL: http://i11b206.p.ssafy.io:5443/
      OPENVIDU_SECRET: MY_SECRET
      DB_URL: jdbc:mysql://db:3306/tastyties
      DB_USERNAME: b206
      DB_PASSWORD: B206!Ssafy206!
      UPLOAD_IMAGE_DIR: /app/files/image
      UPLOAD_VIDEO_DIR: /app/files/video
      FILE_SERVER_URL: http://localhost:8080/api/v1/files
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_ACCESS_KEY: AKIA5P7FDIJH7RU6Q2OZ
      AWS_SECRET_KEY: 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
      AWS_BUCKET_NAME: teamcook-bucket
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - shared_network

  tastytieschat:
    image: seminss/tastytiescaht:latest
    container_name: tastytieschat
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - rabbitmq
      - redis
    environment:
      SERVER_PORT: 8081
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: tastyties
      MONGO_USERNAME: b206
      MONGO_PASSWORD: B206!Ssafy206!
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      OPENAI_SECRET_KEY: JnS85SLEnE9fHH7irPu2T3BlbkFJrLcxXP5PpBPZQi79tvXY
      SPEECH_FLOW_KEY_ID: wnwh8a4z7zqsRKF3
      SPEECH_FLOW_KEY_SECRET: yTvItNNCQGeeQAH8
      FFMPEG_PATH: /usr/local/bin/ffmpeg
      CLOVA_CLIENT_ID: 4e63vkv6t1
      CLOVA_CLIENT_SECRET: 8pzPaUwrrK0PabkbT0k4zp3Uk66aYtFfydE5obSp
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - shared_network

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: B206!Ssafy206!Root1234$
      MYSQL_DATABASE: tastyties
      MYSQL_USER: b206
      MYSQL_PASSWORD: B206!Ssafy206!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: B206!Ssafy206!Root1234$
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shared_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shared_network

volumes:
  mysql_data:
  mongo_data:
  redis_data:

networks:
  shared_network:
    external: true
